# permissions for end users to view kongapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kongapi-viewer-role
rules:
- apiGroups:
  - api.luizalabs-kong
  resources:
  - kongapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.luizalabs-kong
  resources:
  - kongapis/status
  verbs:
  - get
