# permissions for end users to edit kongapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kongapi-editor-role
rules:
- apiGroups:
  - api.luizalabs-kong
  resources:
  - kongapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.luizalabs-kong
  resources:
  - kongapis/status
  verbs:
  - get
