apiVersion: api.luizalabs-kong/v1alpha1
kind: KongAPI
metadata:
  name: kongapi-sample
spec:
  targetRef:
    apiVersion: v1
    kind: Deployment
    name: kong-config
  config: |
    services:
      - name: bets-api-v1
        url: "http://bets.bets.svc.cluster.local:9999"
        retries: 3
        tags:
        - bets-apps
        routes:
          - name: pets
            paths:
              - /pets
            methods:
              - POST
              - GET
        plugins:
          - name: prometheus
          - name: rate-limiting
            config:
              second: 1000
              policy: local
              hide_client_headers: true
          - name: correlation-id
            config:
              header_name: Kong-Request-ID
              generator: uuid#counter
              echo_downstream: true
          - name: tcp-log
            config:
              host: fluentd.logging.svc.cluster.local
              port: 24224




